import "./index.css"

export { StackJob } from "./components/stack-job/StackJob"
export type { StackJobProps } from "./components/stack-job/StackJob"
export { JobHead } from "./components/stack-job/layers/JobHead"
export { JobMeta } from "./components/stack-job/layers/JobMeta"
export { JobSection } from "./components/stack-job/layers/JobSection"
export { JobBase } from "./components/stack-job/layers/JobBase"
export { InView } from "./components/primitives/in-view"
export { Grain, Dots, CornerTicks, Sheen, Accent, MonoLabel, SectionShell, SectionHead, Ordinal } from "./components/primitives/handcraft"
