/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        "steel": "hsl(var(--steel))",
        "steel-deep": "hsl(var(--steel-deep))",
        "brass": "hsl(var(--brass))",
        "vault-face": "hsl(var(--vault-face))",
        brand: { DEFAULT: "hsl(var(--brand))", foreground: "hsl(var(--brand-foreground))" },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))", muted: "hsl(var(--success-muted))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))", muted: "hsl(var(--warning-muted))" },
        "steel": "hsl(var(--steel))",
        "steel-deep": "hsl(var(--steel-deep))",
        "brass": "hsl(var(--brass))",
        "vault-face": "hsl(var(--vault-face))",
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
      fontFamily: { sans: ["var(--font-sans)"], display: ["var(--font-display)"], mono: ["var(--font-mono)"] },
      fontWeight: { medium: "600", semibold: "700", bold: "800" },
      fontSize: {
        xs: ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        sm: ["13.5px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "600" }],
        base: ["15px", { lineHeight: "22px", letterSpacing: "-0.018em", fontWeight: "500" }],
        lg: ["17px", { lineHeight: "26px", letterSpacing: "-0.022em", fontWeight: "600" }],
        xl: ["20px", { lineHeight: "28px", letterSpacing: "-0.025em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
